const DB_NAME='POSliteDB';const DB_VERSION=1;let db;let state={products:[],sales:[],customers:[],expenses:[],settings:{storeName:'POSlite Store',owner:'',address:'',defaultLowStock:5},cart:[],reportRows:[]};let dialogHandler=null;

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const money=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(n||0));const num=n=>Number(n||0);const nowIso=()=>new Date().toISOString();const dateOnly=d=>new Date(d).toISOString().slice(0,10);const today=()=>dateOnly(new Date());const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));

function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function req(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('products'))d.createObjectStore('products',{keyPath:'id'});if(!d.objectStoreNames.contains('sales'))d.createObjectStore('sales',{keyPath:'id'});if(!d.objectStoreNames.contains('customers'))d.createObjectStore('customers',{keyPath:'id'});if(!d.objectStoreNames.contains('expenses'))d.createObjectStore('expenses',{keyPath:'id'});if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
async function getAll(name){return req(store(name).getAll())}async function put(name,value){return req(store(name,'readwrite').put(value))}async function del(name,id){return req(store(name,'readwrite').delete(id))}async function clearStore(name){return req(store(name,'readwrite').clear())}

async function init(){db=await openDB();const saved=await req(store('settings').get('store'));if(saved?.value)state.settings={...state.settings,...saved.value};else await put('settings',{key:'store',value:state.settings});bindUI();setDefaultDates();await refreshAll();updateClock();setInterval(updateClock,30000);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});}
async function refreshAll(){[state.products,state.sales,state.customers,state.expenses]=await Promise.all(['products','sales','customers','expenses'].map(getAll));state.products.sort((a,b)=>a.name.localeCompare(b.name));state.sales.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));state.customers.sort((a,b)=>a.name.localeCompare(b.name));state.expenses.sort((a,b)=>new Date(b.date)-new Date(a.date));renderAll()}
function renderAll(){renderCategories();renderDashboard();renderProducts();renderInventory();renderCustomers();renderExpenses();renderPOS();renderAnalytics();runReport();renderSettings()}

function bindUI(){
  $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
  $('#posSearch').addEventListener('input',renderPOSProducts);$('#posCategory').addEventListener('change',renderPOSProducts);$('#productSearch').addEventListener('input',renderProducts);$('#productCategory').addEventListener('change',renderProducts);
  $('#discountInput').addEventListener('input',renderCart);$('#cashInput').addEventListener('input',renderCart);$('#paymentType').addEventListener('change',()=>{const credit=$('#paymentType').value==='credit';$('#cashFields').hidden=credit;$('#creditFields').hidden=!credit;renderCart()});
  $('#clearCartBtn').addEventListener('click',()=>{state.cart=[];renderCart()});$('#checkoutBtn').addEventListener('click',checkout);
  $('#addProductBtn').addEventListener('click',()=>productDialog());$('#stockAdjustBtn').addEventListener('click',stockDialog);$('#addCustomerBtn').addEventListener('click',customerDialog);$('#addExpenseBtn').addEventListener('click',expenseDialog);
  $('#settingsForm').addEventListener('submit',saveSettings);$('#exportPosBtn').addEventListener('click',exportPos);$('#importPosInput').addEventListener('change',importPos);
  $('#analyticsRange').addEventListener('change',renderAnalytics);$('#runReportBtn').addEventListener('click',runReport);$('#exportReportBtn').addEventListener('click',exportReportCSV);
  $('#dialogForm').addEventListener('submit',e=>{e.preventDefault();if(dialogHandler)dialogHandler(new FormData(e.currentTarget))});
  document.addEventListener('click',async e=>{const p=e.target.closest('[data-add-product]');if(p)return addToCart(p.dataset.addProduct);const a=e.target.closest('[data-action]');if(!a)return;const {action,id}=a.dataset;if(action==='edit-product')productDialog(state.products.find(x=>x.id===id));if(action==='delete-product')await deleteProduct(id);if(action==='adjust-product')stockDialog(id);if(action==='pay-credit')paymentDialog(id);if(action==='delete-customer')await deleteCustomer(id);if(action==='delete-expense')await deleteExpense(id);});
}
function showView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#sidebar').classList.remove('open');if(view==='analytics')renderAnalytics();if(view==='reports')runReport()}
function updateClock(){$('#clockText').textContent=new Date().toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'})}
function setDefaultDates(){const d=new Date();const first=new Date(d.getFullYear(),d.getMonth(),1);$('#reportFrom').value=dateOnly(first);$('#reportTo').value=today()}
function renderCategories(){const cats=[...new Set(state.products.map(p=>p.category).filter(Boolean))].sort();['#posCategory','#productCategory'].forEach(sel=>{const current=$(sel).value;$(sel).innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');$(sel).value=cats.includes(current)?current:''});$('#creditCustomer').innerHTML='<option value="">Select customer</option>'+state.customers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} — ${money(c.balance)}</option>`).join('')}

function renderDashboard(){const todays=state.sales.filter(s=>dateOnly(s.createdAt)===today());const sales=todays.reduce((a,s)=>a+num(s.total),0);const profit=todays.reduce((a,s)=>a+s.items.reduce((x,i)=>x+(num(i.price)-num(i.cost))*num(i.qty),0)-num(s.discount),0);const credit=state.customers.reduce((a,c)=>a+num(c.balance),0);$('#kpiSales').textContent=money(sales);$('#kpiTransactions').textContent=todays.length;$('#kpiProfit').textContent=money(profit);$('#kpiCredit').textContent=money(credit);const low=state.products.filter(p=>num(p.stock)<=num(p.lowStock)).sort((a,b)=>a.stock-b.stock).slice(0,6);$('#lowStockList').innerHTML=low.length?low.map(p=>`<div class="list-row"><div><strong>${escapeHtml(p.name)}</strong><div class="muted">${num(p.stock)} ${escapeHtml(p.unit||'pc')} left</div></div><span class="badge ${num(p.stock)<=0?'out':'low'}">${num(p.stock)<=0?'Out':'Low'}</span></div>`).join(''):'<div class="empty">No low-stock products.</div>';$('#recentSalesList').innerHTML=state.sales.length?state.sales.slice(0,6).map(s=>`<div class="list-row"><div><strong>${escapeHtml(s.number)}</strong><div class="muted">${new Date(s.createdAt).toLocaleString()}</div></div><strong>${money(s.total)}</strong></div>`).join(''):'<div class="empty">No sales yet.</div>'}

function filteredProducts(){const q=$('#productSearch').value.trim().toLowerCase(),cat=$('#productCategory').value;return state.products.filter(p=>(!q||`${p.name} ${p.category}`.toLowerCase().includes(q))&&(!cat||p.category===cat))}
function renderProducts(){const rows=filteredProducts();$('#productTableBody').innerHTML=rows.length?rows.map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong></td><td>${escapeHtml(p.category||'—')}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${num(p.stock)}</td><td>${escapeHtml(p.unit||'pc')}</td><td class="actions"><button class="table-btn" data-action="edit-product" data-id="${p.id}">Edit</button><button class="table-btn" data-action="delete-product" data-id="${p.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No products yet. Add your first product.</td></tr>'}
function productDialog(product=null){openDialog(product?'Edit Product':'Add Product',[
  {name:'name',label:'Product name',required:true,value:product?.name||''},{name:'category',label:'Category',value:product?.category||''},{name:'cost',label:'Cost price',type:'number',step:'0.01',min:'0',required:true,value:product?.cost??0},{name:'price',label:'Selling price',type:'number',step:'0.01',min:'0',required:true,value:product?.price??0},{name:'stock',label:'Current stock',type:'number',step:'0.01',min:'0',required:true,value:product?.stock??0},{name:'unit',label:'Unit',value:product?.unit||'pc'},{name:'lowStock',label:'Low-stock level',type:'number',step:'0.01',min:'0',value:product?.lowStock??state.settings.defaultLowStock}
],async f=>{const data={id:product?.id||uid('prd'),name:String(f.get('name')).trim(),category:String(f.get('category')).trim(),cost:num(f.get('cost')),price:num(f.get('price')),stock:num(f.get('stock')),unit:String(f.get('unit')).trim()||'pc',lowStock:num(f.get('lowStock')),createdAt:product?.createdAt||nowIso(),updatedAt:nowIso()};if(!data.name)return toast('Product name is required.');await put('products',data);closeDialog();toast(product?'Product updated.':'Product added.');await refreshAll()})}
async function deleteProduct(id){const used=state.sales.some(s=>s.items.some(i=>i.productId===id));if(used)return toast('Cannot delete a product already used in sales.');if(!confirm('Delete this product?'))return;await del('products',id);toast('Product deleted.');await refreshAll()}

function renderInventory(){const low=state.products.filter(p=>num(p.stock)<=num(p.lowStock)).length,out=state.products.filter(p=>num(p.stock)<=0).length,value=state.products.reduce((a,p)=>a+num(p.stock)*num(p.cost),0);$('#invProducts').textContent=state.products.length;$('#invLow').textContent=low;$('#invOut').textContent=out;$('#invValue').textContent=money(value);$('#inventoryTableBody').innerHTML=state.products.length?state.products.map(p=>{const status=num(p.stock)<=0?['Out of stock','out']:num(p.stock)<=num(p.lowStock)?['Low stock','low']:['In stock','ok'];return`<tr><td><strong>${escapeHtml(p.name)}</strong><div class="muted">${escapeHtml(p.category||'')}</div></td><td>${num(p.stock)} ${escapeHtml(p.unit||'pc')}</td><td>${num(p.lowStock)}</td><td><span class="badge ${status[1]}">${status[0]}</span></td><td>${money(num(p.stock)*num(p.cost))}</td><td><button class="table-btn" data-action="adjust-product" data-id="${p.id}">Adjust</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No inventory yet.</td></tr>'}
function stockDialog(id=''){const opts=state.products.map(p=>({value:p.id,text:p.name}));openDialog('Stock Adjustment',[{name:'productId',label:'Product',type:'select',options:opts,value:id,required:true},{name:'mode',label:'Adjustment',type:'select',options:[{value:'add',text:'Add stock'},{value:'remove',text:'Remove stock'},{value:'set',text:'Set exact stock'}]},{name:'quantity',label:'Quantity',type:'number',step:'0.01',min:'0',required:true,value:0}],async f=>{const p=state.products.find(x=>x.id===f.get('productId'));if(!p)return toast('Select a product.');const q=num(f.get('quantity')),mode=f.get('mode');let stock=num(p.stock);if(mode==='add')stock+=q;if(mode==='remove')stock=Math.max(0,stock-q);if(mode==='set')stock=q;p.stock=stock;p.updatedAt=nowIso();await put('products',p);closeDialog();toast('Inventory updated.');await refreshAll()})}

function renderPOS(){renderPOSProducts();renderCart();renderCategories()}
function renderPOSProducts(){const q=$('#posSearch').value.trim().toLowerCase(),cat=$('#posCategory').value;const rows=state.products.filter(p=>(!q||`${p.name} ${p.category}`.toLowerCase().includes(q))&&(!cat||p.category===cat));$('#posProductGrid').innerHTML=rows.length?rows.map(p=>`<button class="product-card ${num(p.stock)<=0?'disabled':''}" data-add-product="${p.id}"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.category||'Uncategorized')} · ${num(p.stock)} ${escapeHtml(p.unit||'pc')}</small><span class="price">${money(p.price)}</span></button>`).join(''):'<div class="empty">No products found.</div>'}
function addToCart(id){const p=state.products.find(x=>x.id===id);if(!p||num(p.stock)<=0)return;const item=state.cart.find(x=>x.productId===id);const current=item?.qty||0;if(current>=num(p.stock))return toast('Not enough stock.');if(item)item.qty++;else state.cart.push({productId:p.id,name:p.name,price:num(p.price),cost:num(p.cost),qty:1});renderCart()}
function renderCart(){const subtotal=state.cart.reduce((a,i)=>a+i.price*i.qty,0),discount=Math.min(num($('#discountInput').value),subtotal),total=Math.max(0,subtotal-discount),cash=num($('#cashInput').value),change=Math.max(0,cash-total);$('#cartList').innerHTML=state.cart.length?state.cart.map((i,n)=>`<div class="cart-item"><div><strong>${escapeHtml(i.name)}</strong><div class="muted">${money(i.price)} × ${i.qty}</div></div><div class="cart-controls"><button data-cart="minus" data-index="${n}">−</button><strong>${i.qty}</strong><button data-cart="plus" data-index="${n}">+</button><button data-cart="remove" data-index="${n}">×</button></div></div>`).join(''):'<div class="empty">Cart is empty.</div>';$('#cartSubtotal').textContent=money(subtotal);$('#cartTotal').textContent=money(total);$('#changeAmount').textContent=money(change);$$('[data-cart]').forEach(b=>b.onclick=()=>{const i=state.cart[num(b.dataset.index)],p=state.products.find(x=>x.id===i.productId);if(b.dataset.cart==='plus'&&i.qty<num(p.stock))i.qty++;if(b.dataset.cart==='minus'){i.qty--;if(i.qty<=0)state.cart.splice(num(b.dataset.index),1)}if(b.dataset.cart==='remove')state.cart.splice(num(b.dataset.index),1);renderCart()})}
async function checkout(){if(!state.cart.length)return toast('Add products to the cart.');const subtotal=state.cart.reduce((a,i)=>a+i.price*i.qty,0),discount=Math.min(num($('#discountInput').value),subtotal),total=Math.max(0,subtotal-discount),paymentType=$('#paymentType').value,cash=num($('#cashInput').value),customerId=$('#creditCustomer').value;if(paymentType==='cash'&&cash<total)return toast('Cash received is less than the total.');if(paymentType==='credit'&&!customerId)return toast('Select a customer for credit sale.');for(const item of state.cart){const p=state.products.find(x=>x.id===item.productId);if(!p||num(p.stock)<item.qty)return toast(`Not enough stock for ${item.name}.`)}const sale={id:uid('sale'),number:`POS-${new Date().toISOString().replace(/\D/g,'').slice(0,14)}`,createdAt:nowIso(),items:state.cart.map(i=>({...i})),subtotal,discount,total,paymentType,cash:paymentType==='cash'?cash:0,change:paymentType==='cash'?Math.max(0,cash-total):0,customerId:paymentType==='credit'?customerId:null};const tx=db.transaction(['products','sales','customers'],'readwrite');const ps=tx.objectStore('products'),ss=tx.objectStore('sales'),cs=tx.objectStore('customers');state.cart.forEach(item=>{const p={...state.products.find(x=>x.id===item.productId)};p.stock=num(p.stock)-item.qty;p.updatedAt=nowIso();ps.put(p)});ss.put(sale);if(paymentType==='credit'){const c={...state.customers.find(x=>x.id===customerId)};c.balance=num(c.balance)+total;c.updatedAt=nowIso();c.history=[...(c.history||[]),{type:'credit',amount:total,date:nowIso(),note:sale.number,saleId:sale.id}];cs.put(c)}await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});state.cart=[];$('#discountInput').value=0;$('#cashInput').value='';toast(`Sale complete: ${money(total)}`);await refreshAll()}

function renderCustomers(){$('#customerTableBody').innerHTML=state.customers.length?state.customers.map(c=>`<tr><td><strong>${escapeHtml(c.name)}</strong></td><td>${escapeHtml(c.contact||'—')}</td><td>${money(c.balance)}</td><td>${new Date(c.updatedAt||c.createdAt).toLocaleDateString()}</td><td class="actions"><button class="table-btn" data-action="pay-credit" data-id="${c.id}">Payment</button><button class="table-btn" data-action="delete-customer" data-id="${c.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No customers yet.</td></tr>'}
function customerDialog(){openDialog('Add Customer',[{name:'name',label:'Customer name',required:true},{name:'contact',label:'Contact (optional)'}],async f=>{const name=String(f.get('name')).trim();if(!name)return toast('Customer name is required.');await put('customers',{id:uid('cus'),name,contact:String(f.get('contact')).trim(),balance:0,history:[],createdAt:nowIso(),updatedAt:nowIso()});closeDialog();toast('Customer added.');await refreshAll()})}
function paymentDialog(id){const c=state.customers.find(x=>x.id===id);if(!c)return;openDialog(`Payment — ${c.name}`,[{name:'amount',label:`Amount (Balance ${money(c.balance)})`,type:'number',step:'0.01',min:'0.01',required:true}],async f=>{const amount=Math.min(num(f.get('amount')),num(c.balance));if(amount<=0)return toast('Enter a valid amount.');c.balance=Math.max(0,num(c.balance)-amount);c.updatedAt=nowIso();c.history=[...(c.history||[]),{type:'payment',amount,date:nowIso(),note:'Customer payment'}];await put('customers',c);closeDialog();toast('Payment recorded.');await refreshAll()})}
async function deleteCustomer(id){const c=state.customers.find(x=>x.id===id);if(num(c?.balance)>0)return toast('Customer still has an outstanding balance.');if(state.sales.some(s=>s.customerId===id))return toast('Cannot delete a customer linked to sales history.');if(!confirm('Delete this customer?'))return;await del('customers',id);toast('Customer deleted.');await refreshAll()}

function renderExpenses(){const thisMonth=today().slice(0,7),todayTotal=state.expenses.filter(e=>dateOnly(e.date)===today()).reduce((a,e)=>a+num(e.amount),0),monthTotal=state.expenses.filter(e=>dateOnly(e.date).startsWith(thisMonth)).reduce((a,e)=>a+num(e.amount),0);$('#expenseToday').textContent=money(todayTotal);$('#expenseMonth').textContent=money(monthTotal);$('#expenseTableBody').innerHTML=state.expenses.length?state.expenses.map(e=>`<tr><td>${dateOnly(e.date)}</td><td>${escapeHtml(e.category)}</td><td>${escapeHtml(e.description||'—')}</td><td>${money(e.amount)}</td><td><button class="table-btn" data-action="delete-expense" data-id="${e.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No expenses yet.</td></tr>'}
function expenseDialog(){openDialog('Add Expense',[{name:'date',label:'Date',type:'date',required:true,value:today()},{name:'category',label:'Category',type:'select',options:['Store Supplies','Electricity','Transportation','Delivery','Repairs','Miscellaneous'].map(x=>({value:x,text:x}))},{name:'description',label:'Description'},{name:'amount',label:'Amount',type:'number',step:'0.01',min:'0.01',required:true}],async f=>{await put('expenses',{id:uid('exp'),date:String(f.get('date')),category:String(f.get('category')),description:String(f.get('description')).trim(),amount:num(f.get('amount')),createdAt:nowIso()});closeDialog();toast('Expense recorded.');await refreshAll()})}
async function deleteExpense(id){if(!confirm('Delete this expense?'))return;await del('expenses',id);toast('Expense deleted.');await refreshAll()}

function rangeData(days){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-days+1);return{sales:state.sales.filter(s=>new Date(s.createdAt)>=start),expenses:state.expenses.filter(e=>new Date(e.date)>=start),start}}
function saleProfit(s){return s.items.reduce((a,i)=>a+(num(i.price)-num(i.cost))*num(i.qty),0)-num(s.discount)}
function renderAnalytics(){const days=num($('#analyticsRange').value||30),{sales,expenses,start}=rangeData(days),salesTotal=sales.reduce((a,s)=>a+num(s.total),0),gross=sales.reduce((a,s)=>a+saleProfit(s),0),expenseTotal=expenses.reduce((a,e)=>a+num(e.amount),0),avg=sales.length?salesTotal/sales.length:0;$('#anSales').textContent=money(salesTotal);$('#anProfit').textContent=money(gross);$('#anAverage').textContent=money(avg);$('#anExpenses').textContent=money(expenseTotal);const productMap={};sales.forEach(s=>s.items.forEach(i=>{const x=productMap[i.productId]||{name:i.name,qty:0,revenue:0};x.qty+=num(i.qty);x.revenue+=num(i.price)*num(i.qty);productMap[i.productId]=x}));const top=Object.values(productMap).sort((a,b)=>b.qty-a.qty).slice(0,7);$('#topProductsList').innerHTML=top.length?top.map((p,i)=>`<div class="list-row"><div><strong>${i+1}. ${escapeHtml(p.name)}</strong><div class="muted">${p.qty} units sold</div></div><strong>${money(p.revenue)}</strong></div>`).join(''):'<div class="empty">Not enough sales data yet.</div>';const credit=state.customers.reduce((a,c)=>a+num(c.balance),0),low=state.products.filter(p=>num(p.stock)<=num(p.lowStock)),net=gross-expenseTotal,insights=[];if(top[0])insights.push(`${top[0].name} is the best-selling product in this period with ${top[0].qty} units sold.`);if(low.length)insights.push(`${low.length} product${low.length>1?'s are':' is'} at or below the reorder level.`);if(credit>0)insights.push(`Outstanding customer credit is ${money(credit)}.`);insights.push(`Estimated net after recorded expenses for this period is ${money(net)}.`);if(sales.length>=2){const half=Math.max(1,Math.floor(days/2));const mid=new Date();mid.setHours(0,0,0,0);mid.setDate(mid.getDate()-half+1);const recent=sales.filter(s=>new Date(s.createdAt)>=mid).reduce((a,s)=>a+num(s.total),0),older=sales.filter(s=>new Date(s.createdAt)<mid).reduce((a,s)=>a+num(s.total),0);if(older>0){const diff=(recent-older)/older*100;insights.push(`Recent sales are ${Math.abs(diff).toFixed(1)}% ${diff>=0?'higher':'lower'} than the earlier part of the selected period.`)}}$('#insightsList').innerHTML=insights.map(x=>`<div class="insight">${escapeHtml(x)}</div>`).join('');renderSalesChart(sales,days,start)}
function renderSalesChart(sales,days,start){const count=Math.min(days,14),map={};for(let i=count-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);map[dateOnly(d)]=0}sales.forEach(s=>{const d=dateOnly(s.createdAt);if(d in map)map[d]+=num(s.total)});const values=Object.entries(map),max=Math.max(1,...values.map(x=>x[1]));$('#salesChart').innerHTML=values.map(([d,v])=>`<div class="bar" title="${d}: ${money(v)}" style="height:${Math.max(4,v/max*180)}px"><span>${d.slice(5)}</span></div>`).join('')}

function runReport(){const from=$('#reportFrom').value||'0000-01-01',to=$('#reportTo').value||'9999-12-31';const sales=state.sales.filter(s=>{const d=dateOnly(s.createdAt);return d>=from&&d<=to}),expenses=state.expenses.filter(e=>{const d=dateOnly(e.date);return d>=from&&d<=to});const salesTotal=sales.reduce((a,s)=>a+num(s.total),0),profit=sales.reduce((a,s)=>a+saleProfit(s),0),expenseTotal=expenses.reduce((a,e)=>a+num(e.amount),0);$('#reportSales').textContent=money(salesTotal);$('#reportProfit').textContent=money(profit);$('#reportExpenses').textContent=money(expenseTotal);$('#reportNet').textContent=money(profit-expenseTotal);state.reportRows=sales;$('#reportTableBody').innerHTML=sales.length?sales.map(s=>`<tr><td>${new Date(s.createdAt).toLocaleString()}</td><td>${escapeHtml(s.number)}</td><td>${s.paymentType==='credit'?'Credit':'Cash'}</td><td>${s.items.reduce((a,i)=>a+num(i.qty),0)}</td><td>${money(s.total)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No sales in this range.</td></tr>'}
function exportReportCSV(){runReport();const header=['Date','Transaction','Payment','Items','Subtotal','Discount','Total'];const rows=state.reportRows.map(s=>[s.createdAt,s.number,s.paymentType,s.items.map(i=>`${i.name} x${i.qty}`).join('; '),s.subtotal,s.discount,s.total]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');downloadBlob(new Blob([csv],{type:'text/csv'}),`POSlite-report-${today()}.csv`)}

function renderSettings(){$('#storeName').value=state.settings.storeName||'';$('#storeOwner').value=state.settings.owner||'';$('#storeAddress').value=state.settings.address||'';$('#defaultLowStock').value=state.settings.defaultLowStock??5}
async function saveSettings(e){e.preventDefault();state.settings={storeName:$('#storeName').value.trim()||'POSlite Store',owner:$('#storeOwner').value.trim(),address:$('#storeAddress').value.trim(),defaultLowStock:num($('#defaultLowStock').value)};await put('settings',{key:'store',value:state.settings});toast('Settings saved.')}
async function exportPos(){const backup={format:'POSlite',schemaVersion:1,backupType:'full',createdAt:nowIso(),appVersion:'0.1.0',store:state.settings,data:{products:state.products,sales:state.sales,customers:state.customers,expenses:state.expenses}};const text=JSON.stringify(backup,null,2);downloadBlob(new Blob([text],{type:'application/json'}),`POSlite-backup-${today()}.pos`);$('#backupStatus').textContent=`Backup exported ${new Date().toLocaleString()}`;toast('.pos backup exported.')}
async function importPos(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.format!=='POSlite'||parsed.schemaVersion!==1||!parsed.data)throw new Error('Invalid POSlite backup format.');const counts=`${parsed.data.products?.length||0} products, ${parsed.data.sales?.length||0} sales, ${parsed.data.customers?.length||0} customers`;if(!confirm(`Import this .pos backup?\n\n${counts}\n\nCurrent local data will be replaced.`))return;const tx=db.transaction(['products','sales','customers','expenses','settings'],'readwrite');for(const name of ['products','sales','customers','expenses']){const s=tx.objectStore(name);s.clear();(parsed.data[name]||[]).forEach(x=>s.put(x))}tx.objectStore('settings').put({key:'store',value:{...state.settings,...(parsed.store||{})}});await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});$('#backupStatus').textContent=`Backup imported: ${file.name}`;toast('Backup restored successfully.');await refreshAll()}catch(err){console.error(err);toast(err.message||'Could not import this .pos file.')}}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function openDialog(title,fields,onSubmit){$('#dialogTitle').textContent=title;$('#dialogFields').innerHTML=fields.map(field=>fieldHtml(field)).join('');dialogHandler=onSubmit;const d=$('#formDialog');d.showModal()}
function closeDialog(){dialogHandler=null;$('#formDialog').close()}
function fieldHtml(f){const attrs=[`name="${escapeHtml(f.name)}"`,f.required?'required':'',f.step?`step="${f.step}"`:'',f.min!==undefined?`min="${f.min}"`:''].filter(Boolean).join(' ');if(f.type==='select'){const opts=(f.options||[]).map(o=>{const obj=typeof o==='string'?{value:o,text:o}:o;return`<option value="${escapeHtml(obj.value)}" ${String(obj.value)===String(f.value??'')?'selected':''}>${escapeHtml(obj.text)}</option>`}).join('');return`<label>${escapeHtml(f.label)}<select ${attrs}>${opts}</select></label>`}return`<label>${escapeHtml(f.label)}<input type="${f.type||'text'}" ${attrs} value="${escapeHtml(f.value??'')}" /></label>`}

window.addEventListener('error',e=>console.error('POSlite error',e.error));init().catch(err=>{console.error(err);document.body.innerHTML='<main style="padding:24px;font-family:system-ui"><h1>POSlite</h1><p>Could not start the local database. Please use a modern browser and reload.</p></main>'});
